### PR TITLE
Gracjan package fix

### PR DESCRIPTION
**Pull request by GracjanZwr**
There were duplicated objects inside package.json file 2x devDependencies, scripte, author, and license . Plus duplicated dependencies so I delete them and clean up the package.json
Pls. check before merging :8ball: .
THX !!

### CODE REVIEW

**Comment by fnicola** [comment]
please can you squash the commits? There is no need to have 2 commits for this change :)

**Comment by GracjanZwr** [comment]
commits squashed :+1:  
Pls. check before merging :8ball: .
THX !!

**Comment by fnicola** [comment]
is this PR, just replacing your changes with the previous version of package.json?

**Comment by GracjanZwr** [comment]
There were duplicated objects inside package.json file 2x devDependencies, scripte, author, and license . Plus duplicated dependencies so I delete them and clean up the package.json

**Pull request merged**
