### PR TITLE
[AVE-18] Show booking moved date with US date format condition

### PR DESCRIPTION
**Pull request by gwenau**
At the moment, the moved booking date is only displaying in UK format. An extra condition has been created to display it in US format.

### CODE REVIEW

**Comment by tomlandia** [comment]
We should always use `L*` formats instead of having conditionals everywhere. Please edit `src/core/javascripts/main.js.coffee` instead.

**Comment by lukeferguson** [comment]
@gwenau see comment from @tomlandia above

**Comment by gwenau** [comment]
Hi @tomlandia,

I attempted to modify the src/core/javascripts/main.js.coffee file but was not getting any results. Calling the country code at that stage only returned an empty string so I added the format condition to the basket_item model.

Pros:
- Potentially, we can set the right US/UK date format here and that could mean that we rely less on the datetime filter

Cons:
- This code will run each time there is a datetime object so it might slow done the processing speed a bit (compared to the previous commit for this pull request)

**Comment by tomlandia** [comment]
We can get rid of the con by moving this code to SettingsService.setCountryCode.

**Comment by gwenau** [comment]
Con has been removed by moving code to SettingsService.setCountryCode.

**Comment by tomlandia** [comment]
Make sure to revert the first commit (f36ece3).
Would be good to do that for all `L*` formats. Luke suggests even embedding [en-gb.js](https://github.com/moment/moment/blob/develop/locale/en-gb.js) and calling `moment.locale('en')`/`moment.locale('en-gb')` (I think American is the default)

**Comment by gwenau** [comment]
I've embedded the moment locale 'en-gb' file in core/javascripts/services/i18n. This seems to be the most logical place to put it. Unless the company code is 'us', the date will be returned in the British format.

**Comment by tomlandia** [comment]
OK just removed a forgotten debugger statement and merged

**Comment by tomlandia** [comment]
After-merge fix: `src/core/javascripts/services/i18n/en-gb.js` was one subdirectory too much to be compiled so I renamed it to `src/core/javascripts/components/moment-en-gb.js` in a10daff

**Pull request merged**
